codecov:
  require_ci_to_pass: true

coverage:
  status:
    project: off
    patch: off

flag_management:
  default_rules:
    carryforward: true

  individual_flags:
    - name: app
      paths:
        - app/src/main/**
      carryforward: true

    - name: domain
      paths:
        - domain/src/main/**
      carryforward: true

    - name: data
      paths:
        - data/src/main/**
      carryforward: true